### ISSUE TITLE
请问，这个是用来转换swagger json吗？

### ISSUE THREAD

**Issue by anlia260** [whq731/swagger-mock-parser#2]
我现在有一段swagger json ，想给转化成  API objcet 。不知道可不可做这件事？

**Comment by whq731** [comment]
抱歉，回复比较晚 github的通知太多没注意看。
这个项目是用来针对swagger的API Object来生成随机模拟数据的。
如果你想转先成API object,可以使用这个项目，我们swagger-jsblade也是用的这个工具（4.0的版本）
https://github.com/BigstickCarpet/swagger-parser
然后可以利用本项目对符合swagger规范的API obejct生成随机模拟数据。
